version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80" # Expõe o servidor na porta 8080
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: contatoDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cypress:
    image: cypress/included:12.0.0
    working_dir: /e2e
    volumes:
      - ./tests/cypress:/e2e
      - ./src:/src
    depends_on:
      - php
    entrypoint: npx cypress run # Executa os testes automaticamente

  jest:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: npm run test

volumes:
  mysql_data:
