name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.laudos.saudesystems.com.br
        user: laudos1
        password: Saudesystems@2013
        localDir: "C:\Users\Luiz Antônio\Documents\teste ssite\saude_site"